---
title: "10. Probability distributions"
output: pdf_document
urlcolor: blue
---

These notes consider the Chapter 10 of the [handbook](https://emotion.utu.fi/tilastotiede/) on various probability distributions.

# Discrete distributions

For random variables with countable number of possible values.

## Binomial distribution

See page 200 for proper definition.

```{=latex}
Useful when a random variable $X$ has exactly two exclusive possible outcomes (e.g. success/fail) with known probabilities $p\in[0,1]$ (success) and $q=1-p$ (fail). For $n\in\mathbb{N}$ trials with $k=0,1,2,\dots ,n$ successes

\begin{displaymath}
X\sim Bin(n,p)
\end{displaymath}

\begin{displaymath}
\mathrm{P}(X=k)=\binom{n}{k}p^kq^{n-k}
\end{displaymath}

\begin{displaymath}
\mathrm{F}(k)=\mathrm{P}(X\leqslant k)=\sum_{i=0}^k\binom{n}{i}p^iq^{n-i}
\end{displaymath}

In the following code examples, equal probabilities are assumed, $n=$ \textbf{size}, $p=$ \textbf{prob} $=0.5$.
```

```{r out.width = "75%", fig.align = "center"}
# Sequence for visualization
binomial_seq <- seq(0, 25, by = 1)

# Functions
binomial_pmf <- dbinom(x = binomial_seq, size = 25, prob = 0.5)
binomial_cdf <- pbinom(q = binomial_seq, size = 25, prob = 0.5)

# Plot
par(mfrow = c(1, 2))
plot(binomial_seq, binomial_pmf, ann = FALSE)
plot(binomial_seq, binomial_cdf, type = "S", ann = FALSE)
```

```{r out.width = "75%", fig.align = "center"}
# Probability for exactly 3 successes out of 10 trials
dbinom(x = 3, size = 10, prob = 0.5)

# Probability for up to 3 successes out of 10 trials
pbinom(q = 3, size = 10, prob = 0.5)

# Simulate 10 times how many successes there is using random numbers
rbinom(n = 10, size = 10, prob = 0.5)

# With large enough n, expected value (np = 5) should become visible
rbinom500 <- rbinom(n = 500, size = 10, prob = 0.5)
hist(rbinom500, xlab = "Number of successes", ylab = "Frequency", main = NULL)
summary(rbinom500)
```

## Poisson distribution

See page 204 for proper definition.

```{=latex}
Useful when estimating amounts in random processes where the expected value $(\lambda)$ is known

\begin{displaymath}
X\sim Poi(\lambda)
\end{displaymath}

\begin{displaymath}
\mathrm{P}(X=k)=\frac{\lambda^ke^{-\lambda}}{k!} \;,\; k=0,1,2,\dots ,n
\end{displaymath}

Note that the Poisson distribution can be used to approximate the binomial distribution when $n$ is large and $p$ is small. In this case, $\lambda=np$ and

\begin{displaymath}
\mathrm{P}(X=k)=\frac{(np)^ke^{-np}}{k!}
\end{displaymath}
```

```{r out.width = "75%", fig.align = "center"}
# Sequence for visualization
poisson_seq <- seq(0, 50, by = 1)

# Functions
poisson_pmf <- dpois(x = poisson_seq, lambda = 20)
poisson_cdf <- ppois(q = poisson_seq, lambda = 20)


# Plot
par(mfrow = c(1, 2))
plot(poisson_seq, poisson_pmf, ann = FALSE)
plot(poisson_seq, poisson_cdf, type = "S", ann = FALSE)
```
```{r out.width = "75%", fig.align = "center"}
# A bridge is crossed by 12 people per minute, on average.
# What is the probability that exactly 16 people crosses it in a minute?
dpois(x = 16, lambda = 12)

# A bridge is crossed by 12 people per minute, on average.
# What is the probability that up to 16 people crosses it in a minute?
ppois(q = 16, lambda = 12)

# Simulate amount of people per minute 10 times
rpois(n = 10, lambda = 12)

# By repeating the observation once every day for a year,
# the expected value (lambda = 12) should become visible
poisson_pedestrians <- rpois(n = 365, lambda = 12)
hist(poisson_pedestrians, breaks = 20,
     xlab = "Number of pedestrians", ylab = "Frequency", main = NULL)

summary(poisson_pedestrians)
```
